{
 "title": "Flink Dashboards for Kafka",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Time Between Poll Max",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_time_between_poll_max{instance=~\"taskmanager.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Between Poll Avg",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_time_between_poll_avg{instance=~\"taskmanager.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_commit_latency_avg{instance=~\"taskmanager.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commits Succeeded",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_commitsSucceeded{instance=~\"taskmanager.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit Sync Time ns Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 13 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_commit_sync_time_ns_total{instance=~\"taskmanager.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commits Failed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 14, "y": 13 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_commitsFailed{instance=~\"taskmanager.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rebalance Rate per Hour",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_failed_rebalance_rate_per_hour{instance=~\"taskmanager.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 25 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_sync_total{instance=~\"taskmanager.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic Partition Current Offset",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 14, "y": 25 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{instance=~\"taskmanager.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions Per Task",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_assigned_partitions{instance=~\"taskmanager.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 37 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_connection_count{instance=~\"taskmanager.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Consumed Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 14, "y": 37 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_bytes_consumed_rate{instance=~\"taskmanager.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}